version: '3'

services:

    jhub:
        image: gesiscss/jupyterhub-jsa:v0.8.1
        deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
          resources:
              limits:
                  cpus: "0.2"
                  memory: 512M
        volumes:
            - path/to/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
        restart: always
        expose:
            - "8000"
        networks:
            - webnet

    nginx-shibboleth:
        depends_on:
            - jhub
        image: gesiscss/nginx-shibboleth:v0.2.2
        deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
          resources:
              limits:
                  cpus: "0.2"
                  memory: 512M
        volumes:
            # add Shibboleth configuration
            - path/to/shibboleth:/etc/shibboleth
            # add nginx configuration
            - path/to/shibboleth_nginx.conf:/etc/nginx/conf.d/shibboleth_nginx.conf
            # below here depends on your project requirements
            # if you want to use shibboleth eds
            - path/to/embedded_discovery_service:/home/shibboleth/embedded_discovery_service
            # if you want to use letsencrypt to enable https
            - /etc/letsencrypt:/etc/letsencrypt
            - /etc/ssl:/etc/ssl
        ports:
            - "80:80"
            - "443:443"
        restart: always
        command: /usr/bin/supervisord --nodaemon --configuration /etc/supervisor/supervisord.conf
        networks:
            - webnet
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
          - "8080:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
          placement:
            constraints: [node.role == manager]
        networks:
          - webnet
networks:
  webnet: