# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/578b3a285708be4de92990403dfd517c01e74a0f/images/hub
FROM jupyterhub/k8s-hub:a3fab36

RUN pip3 install --no-cache-dir jhub_shibboleth_auth==1.2.0