# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/0e1225e5258681227000414d4f9ea3c20b89b76c/images/hub
FROM jupyterhub/k8s-hub:0e1225e

RUN pip3 install --no-cache-dir git+https://github.com/gesiscss/jhub_shibboleth_auth.git@master#egg=jhub_shibboleth_auth